export interface RespuestaSolicitudMantenimiento {
  "DES_USO": string,
  "DES_NUMMOTOR": string,
  "NOM_VELATORIO": string,
  "ID_MTTOMODALIDAD": number,
  "ID_MTTOMODALIDAD_DET": number,
  "DES_PLACAS": string,
  "DES_NUMSERIE": string,
  "DES_DELEGACION": string,
  "DES_MTTO_TIPO": string,
  "DES_MTTO_CORRECTIVO": string,
  "ID_MTTO_TIPO": number,
  "ID_MTTOESTADO": number,
  "DES_MODELO": string,
  "DES_MODALIDAD": string,
  "ID_MTTO_SOLICITUD": number,
  "DES_MARCA": string,
  "IND_ESTATUS": boolean,
  "ID_VELATORIO": number,
  "DES_MTTOESTADO": string,
  "FEC_REGISTRO": string,
  "ID_VEHICULO": number,
  "ID_DELEGACION": number,
  "FEC_ALTA": string,
  "IND_ACTIVO": boolean,
  DES_SUBMARCA: string
}
