export interface VehiculoMantenimiento {
  FEC_REGISTRO?: string;
  DESCRIPCION: string,
  DES_MARCA: string,
  DES_MODALIDAD: string,
  DES_MODELO: string,
  DES_MTTOESTADO: string,
  DES_MTTO_TIPO: string,
  DES_NIVELOFICINA: string,
  DES_NUMMOTOR: string,
  DES_NUMSERIE: string,
  DES_PLACAS: string,
  DES_SUBMARCA: string,
  DES_USO: string,
  ID_OFICINA: number,
  ID_USOVEHICULO: number,
  ID_VEHICULO: number,
  ID_VELATORIO: number,
  IMPORTE_PRIMA: number,
  IND_ESTATUS: boolean,
  DES_VELATORIO: string  | null,
  TOTAL: number,
  TOTAL_VEHICULOS?: number | null,
  ID_MTTO_SOLICITUD: number | null,
  ID_MTTOVERIFINICIO: number,
  ID_MTTO_REGISTRO: number | null,
  ID_MTTOVEHICULAR: number,
  DES_NIVEL_ACEITE?: string,
  DES_NIVEL_AGUA?: string,
  DES_NIVEL_BATERIA?: string,
  DES_NIVEL_CODIGOFALLO?: string,
  DES_NIVEL_COMBUSTIBLE?: string,
  verificacionDia: string,
  DES_DELEGACION: string
  // Campos faltantes
  KILOMETRAJE?: string,
  FECHA_MANTENIMIENTO?: string,
  ID_MTTOESTADO?: number,
}
