export interface SolicitudBeneficiario {
  validaIne: boolean,
  nombreIne: string | null,
  validaActa: boolean,
  nombreActa: string | null,
  documento: string | null,
  idContratanteBeneficiario: number,
  rfc: string,
  curp: string,
  nombre: string,
  primerApe: string,
  segunApe: string,
  idSexo: number,
  otroSexo: string,
  fechaNaciemiento: string,
  idPais: number,
  idEstado: number,
  telefono: string,
  correo: string,
  idPersona: number
}

export interface SolicitudEmpresa {
  nombre: string,
  razonSocial: string,
  rfc: string,
  idPais: number,
  telefono: string,
  correo: string,
  idEmpresa: number,
  idConvenioPF: number,
  calle: string,
  numExt: string,
  numInt: string,
  cp: string,
  colonia: string,
  municipio: string,
  estado: string,
  idDomicilio: number
}

export interface SolicitudPersona {
  rfc: string,
  curp: string,
  nombre: string,
  primerApe: string,
  segunApe: string,
  idSexo: number,
  otroSexo: string,
  fechaNaciemiento: string,
  idPais: number,
  idEstado: number,
  telefono: string,
  correo: string,
  idPersona: number,
  calle: string,
  numExt: string,
  numInt: string,
  cp: string,
  colonia: string,
  municipio: string,
  estado: string,
  idDomicilio: number,
  idEnfermedad: number,
  otraEnfermedad: null,
  idPaquete: number,
  idContraPaqPF: number,
  matricula: string | null,
  idContrantante: number,
  idPromotor: number,
  idConvenioPF: number,
  idValidaDocumento: number,
  nombreCurp: string | null,
  archivoCurp: string | null,
  validaCurp: boolean,
  nombreRfc: string | null,
  archivoRfc: string | null,
  validaRfc: boolean,
  nombreIne: string | null,
  archivoIne: string | null,
  validaIne: boolean
}
