export interface PagoGestion {
  desEstatus: string,
  desEstatusPago: string,
  desFlujo: string,
  desMetodoPago: string,
  fecha: string,
  folio: string,
  id: number,
  idEstatus: string,
  idEstatusPago: number,
  idFlujo: number,
  idMetodoPago: number,
  nomContratante: string,
  soloVisual: number,
  total: number,
}
