import {BeneficiarioInterface} from "./beneficiario.interface";
import {PersonaInterface} from "./persona.interface";

export interface ModeloGuardarPorPersona
{
  idVelatorio?:string,
  nombreVelatorio?:string,
  indTipoContratacion?:string,
  idPromotor?:string,
  matricula?:string,
  rfc?:string,
  curp?:string,
  nss?:string,
  numIne?:string,
  nombre?:string,
  primerApellido?:string,
  segundoApellido?:string,
  sexo?:string,
  otroSexo?:string,
  fechaNacimiento?:string,
  tipoPersona?:string,
  calle?:string,
  numeroExterior?:string,
  numeroInterior?:string,
  cp?:string,
  colonia?:string,
  municipio?:string,
  estado?:string,
  pais?:string,
  correoElectronico?:string,
  telefono?:string,
  enfermedadPreexistente?:string,
  otraEnfermedad?:string,
  paquete?:string,
  persona?: PersonaInterface,
  idPersona?: string,
  idDomicilio?: string,
  idContratante?: string,
  numeroConvenio?: string,
  rfcCurp?: string,
}
