export interface RegistroRFC {
  razonSocial: string,
  regimenFiscal: string,
  tipoPersona: string,
  domicilioFiscal: {
    "calle": "ABRAHAM CASTELLANOS",
    "email": "ircero@gmail.com",
    "paisResidencia": "ESTADOS UNIDOS MEXICANOS",
    "telefono1": "953-5329968",
    "telefono2": "",
    "calr": "71",
    "ccrh": "",
    "cp": "69005",
    "dalr": "OAXACA 1",
    "dcrh": "",
    "caractDomicilio": "",
    "ccolonia": "69005007",
    "centFed": "20",
    "clocalidad": "69005038",
    "cmunicipio": "39",
    "dcolonia": "DEL MAESTRO 1A SECCION",
    "dentFed": "OAXACA",
    "dentreCalle1": "16 DE SEPTIEMBRE",
    "dentreCalle2": "RAFAEL RAMIREZ",
    "dinmueble": "CASA HABITACIÓN",
    "dlocalidad": "HEROICA CIUDAD DE HUAJUAPAN DE LEON",
    "dmunicipio": "HEROICA CIUDAD DE HUAJUAPAN DE LEON",
    "dreferencia": "A UN COSTADO DE LA TIENDA DEL ISSSTE3.",
    "dvialidad": "CALLE",
    "faltaDom": "2015-04-27",
    "nexterior": "69",
    "ninterior": "SIN NUMERO",
    "tinmueble": "2",
    "ttel1": "Fijo",
    "ttel2": "",
    "tvialidad": "5"
  }
}
